version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=school_payment_db
    ports:
      - "5432:5432"

  backend:
    build: ./server
    command: uvicorn server.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./server:/app/server
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/school_payment_db
      - SECRET_KEY=supersecretkey
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  worker:
    build: ./server
    command: celery -A worker.celery_app worker --loglevel=info
    volumes:
      - ./server:/app/server
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/school_payment_db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - backend
      - redis

  frontend:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
