"""baseline

Revision ID: 1454e7947d03
Revises: 651b67fce830
Create Date: 2026-09-18 15:02:41.822161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1454e7947d03'
down_revision: Union[str, Sequence[str], None] = '651b67fce830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paystack_public_key', sa.String(), nullable=True),
    sa.Column('paystack_secret_key', sa.String(), nullable=True),
    sa.Column('platform_fee_percentage', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_settings'))
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_settings_id'), ['id'], unique=False)

    op.create_table('platform_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('amount_due', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('billing_period', sa.String(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_platform_invoices_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_invoices'))
    )
    with op.batch_alter_table('platform_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platform_invoices_id'), ['id'], unique=False)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('payment_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_phone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('subscription_plan', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('subscription_due_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('modules_enabled', sa.String(), nullable=True))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_column('modules_enabled')
        batch_op.drop_column('subscription_due_date')
        batch_op.drop_column('subscription_plan')
        batch_op.drop_column('created_at')
        batch_op.drop_column('status')
        batch_op.drop_column('contact_phone')

    with op.batch_alter_table('payment_attempts', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('platform_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_invoices_id'))

    op.drop_table('platform_invoices')
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_id'))

    op.drop_table('system_settings')
    # ### end Alembic commands ###
