"""Sprint 1: Invoicing and Payment Attempts

Revision ID: 2c03216a5686
Revises: c0ee1e56d2c2
Create Date: 2026-06-18 11:16:29.292921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c03216a5686'
down_revision: Union[str, Sequence[str], None] = 'c0ee1e56d2c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discounts', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_discounts_school_id', 'schools', ['school_id'], ['id'])

    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_notification_logs_school_id', 'schools', ['school_id'], ['id'])

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classroom_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_students_classroom_id', 'classrooms', ['classroom_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint('fk_students_classroom_id', type_='foreignkey')
        batch_op.drop_column('classroom_id')

    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_notification_logs_school_id', type_='foreignkey')
        batch_op.drop_column('school_id')

    with op.batch_alter_table('discounts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_discounts_school_id', type_='foreignkey')

    # ### end Alembic commands ###
