"""Add class-level virtual accounts and unmatched payments

Revision ID: a752435d1878
Revises: 2c03216a5686
Create Date: 2026-06-24 22:05:10.056864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a752435d1878'
down_revision: Union[str, Sequence[str], None] = '2c03216a5686'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_discounts_school_id_schools'), 'schools', ['school_id'], ['id'])

    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allowed_installment_options', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('enable_late_fees', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('late_fee_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('late_fee_grace_period_days', sa.Integer(), nullable=True))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('profile_picture_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('home_address', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_phone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('blood_group', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('genotype', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('allergies', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('medical_conditions', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('admission_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_balance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('auto_pay_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('auto_pay_enabled')
        batch_op.drop_column('credit_balance')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('admission_date')
        batch_op.drop_column('medical_conditions')
        batch_op.drop_column('allergies')
        batch_op.drop_column('genotype')
        batch_op.drop_column('blood_group')
        batch_op.drop_column('emergency_contact_phone')
        batch_op.drop_column('emergency_contact_name')
        batch_op.drop_column('home_address')
        batch_op.drop_column('profile_picture_url')
        batch_op.drop_column('gender')
        batch_op.drop_column('date_of_birth')

    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_column('late_fee_grace_period_days')
        batch_op.drop_column('late_fee_percentage')
        batch_op.drop_column('enable_late_fees')
        batch_op.drop_column('allowed_installment_options')

    with op.batch_alter_table('discounts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_discounts_school_id_schools'), type_='foreignkey')
        batch_op.drop_column('school_id')

    # ### end Alembic commands ###
